### ISSUE TITLE
[Server Kick] Player kicks out of server when creating waypoint

### ISSUE THREAD

**Issue by WinZZer** [gigaherz/HudCompass#2]
When trying to create waypoint with map on banner player kicks out of server with "Internal server error".
No additional mods installed.
[server_log.txt](https://github.com/gigaherz/HudCompass/files/5842841/server_log.txt)

**Comment by gigaherz** [comment]
Sorry for the delay. I notice that one of the methods I call only exists on the client. I'm about to publish a new update which should fix this.

**Comment by gigaherz** [comment]
v0.1.2 is up on curseforge.

**Comment by WinZZer** [comment]
Thanks!
