### ISSUE TITLE
New Version dont show waypoints

### ISSUE THREAD

**Issue by jajajafeti** [gigaherz/HudCompass#3]
Hey, i just downloaded the latest version HudCompass-1.16.5-0.1.2 and wanted to add waypoints in the edit menu, but when I save them they dont show on the hud nor in the editor (if I open it again). So I thought they dont get saved, I was wrong. Becaus I downloaded HudCompass-1.16.4-0.1.1 and the waiponts showed up normaly.

**Comment by gigaherz** [comment]
Sorry for taking so long. I finally realized what was wrong. v0.1.3 has been uploaded and is pending review on curseforge.
